# Dependencies
plugins:
  - jekyll-sitemap

# theme
theme: jekyll-theme-minimal
title: 'Swift Unwrapped'
description: 'Discussions on the Swift programming language and other projects at Swift.org'
logo: /img/logo.jpg
show_downloads: false
twitter_handle: "@swift_unwrapped"
twitter_url: https://twitter.com/swift_unwrapped

# File rules
exclude:
  - Makefile
  - LICENSE
  - README.md
  - scripts/
  - .github/

# Site
permalink: /episodes/:title/
sass:
  style: compressed

url: https://swiftunwrapped.github.io

timezone: America/Los_Angeles
