name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Site
    runs-on: macos-latest # https://github.com/actions/virtual-environments
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: versions
        run: |
          ruby --version
          gem --version
          bundler --version

      - name: cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --without=documentation --jobs 4 --retry 3

      - name: jekyll build
        run: bundle exec jekyll build
